[package]
name = "parser-test"
version = "0.1.0"
edition = "2021"
authors = ["Roman Isaikin <romix.lab@gmail.com>"]
license = "MIT"
description = "Declarative tester for parsers"
repository = "https://github.com/romixlab/parser-test"

[dependencies]
